# Generated by Django 2.2.16 on 2022-11-11 20:03

import django.core.validators
from django.db import migrations, models
import reviews.models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(reviews.validators.get_year)], verbose_name='Год произведения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=reviews.models.UsernameField(max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
